services:
    # сервис основного приложения
    app:
        build: .
        image: portfolio
        env_file:
            - .env
        volumes:
            - ./src:/src
            - ./media:/media
            - ./logs:/logs
            - ./docs:/docs
        working_dir: /src/
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        links:
            - db
        depends_on:
            - db

    # база данных
    db:
        image: postgres:14-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
