# Generated by Django 4.1.1 on 2022-09-26 13:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "verbose_name": "Сообщение блога",
                "verbose_name_plural": "Сообщения блога",
            },
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Содержимое сообщения"
            ),
        ),
    ]
