# Generated by Django 4.1.1 on 2022-09-20 15:45
from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления записи"
                    ),
                ),
                (
                    "resume",
                    models.CharField(
                        help_text="Резюме",
                        max_length=255,
                        verbose_name="Резюме",
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        help_text="GitHub",
                        max_length=255,
                        verbose_name="GitHub",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Электронная почта",
                        max_length=255,
                        verbose_name="Электронная почта",
                    ),
                ),

            ],
            options={
                "verbose_name": "Информация о пользователе",
                "verbose_name_plural": "Информация о пользователе",
            },
        ),
    ]
