# Generated by Django 4.1.7 on 2023-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "verbose_name": "Информация о пользователе",
                "verbose_name_plural": "Информация о пользователях",
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.CharField(max_length=255, verbose_name="Электронная почта"),
        ),
        migrations.AlterField(
            model_name="person",
            name="github",
            field=models.CharField(max_length=255, verbose_name="GitHub"),
        ),
        migrations.AlterField(
            model_name="person",
            name="resume",
            field=models.CharField(max_length=255, verbose_name="Резюме"),
        ),
    ]
