# Generated by Django 4.1.7 on 2023-03-10 09:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="full_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default=0, verbose_name="Полное описание"
            ),
            preserve_default=False,
        ),
    ]
